<a href="https://colab.research.google.com/github/khajizatu-sidqiyah/pm-turi2-preprocessing-KhajizatuSidqiyah/blob/main/PM_P4_KhajizatuSidqiyah_2488010044.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np

# Dataset karyawan (sengaja mengandung masalah kualitas)
data = {
    'usia'      : [25, 32, np.nan, 45, 28, 51, 38, np.nan, 29, 41],
    'pendapatan': [4_000_000, 7_500_000, 5_200_000, 12_000_000, 4_800_000,
                   15_000_000, 8_100_000, 6_300_000, np.nan, 9_900_000],
    'pendidikan': ['SMA','S1','SMA','S2','SMA','S2','S1','S1','SMA','S2'],  # ordinal
    'kota'      : ['Bandung','Jakarta','Bandung','Surabaya','Jakarta',
                   'Surabaya','Jakarta','Bandung','Bandung','Jakarta'],    # nominal
    'membeli'   : ['Tidak','Ya','Tidak','Ya','Tidak','Ya','Ya','Tidak','Tidak','Ya']  # target
}
df = pd.DataFrame(data)
df

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2   NaN   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7   NaN   6300000.0         S1   Bandung   Tidak
8  29.0         NaN        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

In [14]:
# langkah 1
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())

df

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2  35.0   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7  35.0   6300000.0         S1   Bandung   Tidak
8  29.0   7500000.0        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

In [15]:
# langkah 2
X = df.drop(columns=['membeli'])
y = df['membeli']

print(X)
print(y)

   usia  pendapatan pendidikan      kota
0  25.0   4000000.0        SMA   Bandung
1  32.0   7500000.0         S1   Jakarta
2  35.0   5200000.0        SMA   Bandung
3  45.0  12000000.0         S2  Surabaya
4  28.0   4800000.0        SMA   Jakarta
5  51.0  15000000.0         S2  Surabaya
6  38.0   8100000.0         S1   Jakarta
7  35.0   6300000.0         S1   Bandung
8  29.0   7500000.0        SMA   Bandung
9  41.0   9900000.0         S2   Jakarta
0    Tidak
1       Ya
2    Tidak
3       Ya
4    Tidak
5       Ya
6       Ya
7    Tidak
8    Tidak
9       Ya
Name: membeli, dtype: object

In [16]:
# langkah 3
X['pendidikan'] = X['pendidikan'].map({'SMA':0,'S1':1,'S2':2}) # ordinal
X = pd.get_dummies(X, columns=['kota'], dtype=int) # nominal
y = y.map({'Tidak':0,'Ya':1})

print(X)
print (y)

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  25.0   4000000.0           0             1             0              0
1  32.0   7500000.0           1             0             1              0
2  35.0   5200000.0           0             1             0              0
3  45.0  12000000.0           2             0             0              1
4  28.0   4800000.0           0             0             1              0
5  51.0  15000000.0           2             0             0              1
6  38.0   8100000.0           1             0             1              0
7  35.0   6300000.0           1             1             0              0
8  29.0   7500000.0           0             1             0              0
9  41.0   9900000.0           2             0             1              0
0    0
1    1
2    0
3    1
4    0
5    1
6    1
7    0
8    0
9    1
Name: membeli, dtype: int64

In [17]:
# langkah 4
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
X, y, test_size=0.3, random_state=42)

print("Jumlah data X_train:", len(X_train))
print("Jumlah data X_test :", len(X_test))
print("Jumlah data y_train:", len(y_train))
print("Jumlah data y_test :", len(y_test))

Jumlah data X_train: 7
Jumlah data X_test : 3
Jumlah data y_train: 7
Jumlah data y_test : 3

In [18]:
# langkah 5
from sklearn.preprocessing import StandardScaler
num = ['usia','pendapatan','pendidikan']
sc = StandardScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num]) # cegah data leakage

print(X_train[num].head())
print(X_test[num].head())

       usia  pendapatan  pendidikan
0 -1.588665   -1.169416   -1.028992
7 -0.044130   -0.325129    0.171499
2 -0.044130   -0.728919   -1.028992
9  0.882592    0.996363    1.371989
4 -1.125304   -0.875751   -1.028992
       usia  pendapatan  pendidikan
8 -0.970851    0.115368   -1.028992
1 -0.507490    0.115368    0.171499
5  2.427127    2.868478    1.371989

In [19]:
# langkah 6

print("Jumlah nilai hilang pada X_train:")
print(X_train.isnull().sum())

print("\nJumlah nilai hilang pada X_test:")
print(X_test.isnull().sum())

print("\nTipe data X_train:")
print(X_train.dtypes)

print("\nStatistik X_train setelah scaling:")
print(X_train.describe())

Jumlah nilai hilang pada X_train:
usia             0
pendapatan       0
pendidikan       0
kota_Bandung     0
kota_Jakarta     0
kota_Surabaya    0
dtype: int64

Jumlah nilai hilang pada X_test:
usia             0
pendapatan       0
pendidikan       0
kota_Bandung     0
kota_Jakarta     0
kota_Surabaya    0
dtype: int64

Tipe data X_train:
usia             float64
pendapatan       float64
pendidikan       float64
kota_Bandung       int64
kota_Jakarta       int64
kota_Surabaya      int64
dtype: object

Statistik X_train setelah scaling:
               usia    pendapatan    pendidikan  kota_Bandung  kota_Jakarta  \
count  7.000000e+00  7.000000e+00  7.000000e+00      7.000000      7.000000
mean   1.110223e-16  1.030921e-16 -1.982541e-17      0.428571      0.428571
std    1.080123e+00  1.080123e+00  1.080123e+00      0.534522      0.534522
min   -1.588665e+00 -1.169416e+00 -1.028992e+00      0.000000      0.000000
25%   -5.847169e-01 -8.023348e-01 -1.028992e+00      0.000000      0.000000
50%   -4.412958e-02 -3.251291e-01  1.714986e-01      0.000000      0.000000
75%    6.509113e-01  6.659903e-01  7.717436e-01      1.000000      1.000000
max    1.500406e+00  1.767234e+00  1.371989e+00      1.000000      1.000000

       kota_Surabaya
count       7.000000
mean        0.142857
std         0.377964
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

In [ ]:
# D. Latihan Mandiri

In [20]:
# soal no 1

# Membuat salinan data awal
df_mean = pd.DataFrame(data)

# Menghitung mean dan median usia
mean_usia = df_mean['usia'].mean()
median_usia = df_mean['usia'].median()

print("Mean usia   :", mean_usia)
print("Median usia :", median_usia)

# Imputasi usia menggunakan mean
df_mean['usia'] = df_mean['usia'].fillna(mean_usia)

# Pendapatan tetap menggunakan median
df_mean['pendapatan'] = df_mean['pendapatan'].fillna(
    df_mean['pendapatan'].median()
)

print("\nData setelah imputasi mean:")
print(df_mean)

Mean usia   : 36.125
Median usia : 35.0

Data setelah imputasi mean:
     usia  pendapatan pendidikan      kota membeli
0  25.000   4000000.0        SMA   Bandung   Tidak
1  32.000   7500000.0         S1   Jakarta      Ya
2  36.125   5200000.0        SMA   Bandung   Tidak
3  45.000  12000000.0         S2  Surabaya      Ya
4  28.000   4800000.0        SMA   Jakarta   Tidak
5  51.000  15000000.0         S2  Surabaya      Ya
6  38.000   8100000.0         S1   Jakarta      Ya
7  36.125   6300000.0         S1   Bandung   Tidak
8  29.000   7500000.0        SMA   Bandung   Tidak
9  41.000   9900000.0         S2   Jakarta      Ya

imputasi menggunakan mean mengisi nilai usia yang hilang dengan rata-rata usia, sedangkan pada Bagian C digunakan median. Mean lebih mudah dipengaruhi oleh nilai ekstrem, sedangkan median lebih tahan terhadap nilai ekstrem.

In [21]:
# soal no 2

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# Membuat X dan y
X_mm = df.drop(columns=['membeli']).copy()
y_mm = df['membeli'].copy()

# Encoding pendidikan
X_mm['pendidikan'] = X_mm['pendidikan'].map({
    'SMA': 0,
    'S1': 1,
    'S2': 2
})

# One-hot encoding kota
X_mm = pd.get_dummies(
    X_mm,
    columns=['kota'],
    dtype=int
)

# Encoding label
y_mm = y_mm.map({
    'Tidak': 0,
    'Ya': 1
})

# Split data
X_train_mm, X_test_mm, y_train_mm, y_test_mm = train_test_split(
    X_mm,
    y_mm,
    test_size=0.3,
    random_state=42
)

# Scaling dengan MinMaxScaler
num = ['usia', 'pendapatan', 'pendidikan']

scaler_mm = MinMaxScaler()

X_train_mm[num] = scaler_mm.fit_transform(X_train_mm[num])
X_test_mm[num] = scaler_mm.transform(X_test_mm[num])

print("Hasil X_train setelah MinMaxScaler:")
print(X_train_mm)

print("\nDescribe X_train:")
print(X_train_mm.describe())

Hasil X_train setelah MinMaxScaler:
   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  0.00      0.0000         0.0             1             0              0
7  0.50      0.2875         0.5             1             0              0
2  0.50      0.1500         0.0             1             0              0
9  0.80      0.7375         1.0             0             1              0
4  0.15      0.1000         0.0             0             1              0
3  1.00      1.0000         1.0             0             0              1
6  0.65      0.5125         0.5             0             1              0

Describe X_train:
           usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  \
count  7.000000    7.000000    7.000000      7.000000      7.000000
mean   0.514286    0.398214    0.428571      0.428571      0.428571
std    0.349660    0.367808    0.449868      0.534522      0.534522
min    0.000000    0.000000    0.000000      0.000000      0.000000
25%    0.325000    0.125000    0.000000      0.000000      0.000000
50%    0.500000    0.287500    0.500000      0.000000      0.000000
75%    0.725000    0.625000    0.750000      1.000000      1.000000
max    1.000000    1.000000    1.000000      1.000000      1.000000

       kota_Surabaya
count       7.000000
mean        0.142857
std         0.377964
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

In [23]:
# soal no 3

# Membuat salinan data
df_kategori = df.copy()

# Menambahkan kolom pengalaman
df_kategori['pengalaman'] = [
    'Pemula',
    'Menengah',
    'Pemula',
    'Berpengalaman',
    'Menengah',
    'Berpengalaman',
    'Menengah',
    'Pemula',
    'Pemula',
    'Berpengalaman'
]

print("Data sebelum one-hot encoding:")
print(df_kategori)

# One-hot encoding kolom pengalaman
df_kategori = pd.get_dummies(
    df_kategori,
    columns=['pengalaman'],
    dtype=int
)

print("\nData setelah one-hot encoding:")
print(df_kategori)

Data sebelum one-hot encoding:
   usia  pendapatan pendidikan      kota membeli     pengalaman
0  25.0   4000000.0        SMA   Bandung   Tidak         Pemula
1  32.0   7500000.0         S1   Jakarta      Ya       Menengah
2  35.0   5200000.0        SMA   Bandung   Tidak         Pemula
3  45.0  12000000.0         S2  Surabaya      Ya  Berpengalaman
4  28.0   4800000.0        SMA   Jakarta   Tidak       Menengah
5  51.0  15000000.0         S2  Surabaya      Ya  Berpengalaman
6  38.0   8100000.0         S1   Jakarta      Ya       Menengah
7  35.0   6300000.0         S1   Bandung   Tidak         Pemula
8  29.0   7500000.0        SMA   Bandung   Tidak         Pemula
9  41.0   9900000.0         S2   Jakarta      Ya  Berpengalaman

Data setelah one-hot encoding:
   usia  pendapatan pendidikan      kota membeli  pengalaman_Berpengalaman  \
0  25.0   4000000.0        SMA   Bandung   Tidak                         0
1  32.0   7500000.0         S1   Jakarta      Ya                         0
2  35.0   5200000.0        SMA   Bandung   Tidak                         0
3  45.0  12000000.0         S2  Surabaya      Ya                         1
4  28.0   4800000.0        SMA   Jakarta   Tidak                         0
5  51.0  15000000.0         S2  Surabaya      Ya                         1
6  38.0   8100000.0         S1   Jakarta      Ya                         0
7  35.0   6300000.0         S1   Bandung   Tidak                         0
8  29.0   7500000.0        SMA   Bandung   Tidak                         0
9  41.0   9900000.0         S2   Jakarta      Ya                         1

   pengalaman_Menengah  pengalaman_Pemula
0                    0                  1
1                    1                  0
2                    0                  1
3                    0                  0
4                    1                  0
5                    0                  0
6                    1                  0
7                    0                  1
8                    0                  1
9                    0                  0

# soal no 4

fit_transform() digunakan pada data latih karena scaler perlu mempelajari parameter dari data latih, seperti mean dan standar deviasi pada StandardScaler. Setelah parameter diperoleh, data uji hanya menggunakan transform() dengan parameter yang sama.

E. Refleksi
1. Mengapa urutan 'split dulu, baru scaling' penting?
2. Kapan label encoding dan kapan one-hot encoding?
3. Apa perbedaan normalisasi dan standardisasi?

jawaban:
1. data harus dibagi menjadi data latih dan data uji terlebih dahulu sebelum melakukan scaling, untuk mencegah kebocoran data. scaler hanya boleh mempelajari di-fit data latih, kemudian digunakan untuk melakukan transform pada data latih dan data uji. jika scaling digunakan sebelum pembagian data, informasi dari data uji dapat ikut masuk ke proses pelatihan.

2. label encoding digunakan untuk data kategorikal yang memiliki urutan atau tingkatan atau bisa disebut ordinal, seperti SMA, S1, dan S2. sedangkan one-hot encoding digunakan untuk data kategorikal yang tidak memiliki urutan, seperti Bandung, Jakarta, dan Surabaya.

3. normalisasi (Min-Max) mengubah nilai data dalam rentang tertentu, biasanya 0-1, sehingga memiliki batas yang jelas tetapi sensitif terhadap outlier. sedangkan standardisasi (z-scrore) mengubah data sehingga memiliki mean mendakati 0 dan standar deviasi 1, secara tidak memiliki batas rentang tertentu.